project:
  type: website
  output-dir: docs

website:
  title: "Onkar Singh"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - about.qmd

format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#CC8899"
    linkcolor: "#ff33f0"
    monofont: courier new
    css: styles.css
    toc: true

editor: visual

